### ISSUE TITLE
Correções relacionadas aos feedbacks do Ponto de Controle 2

### ISSUE THREAD

**Issue by gustable42** [Requisitos-de-Software/2019.2-Rappi#10]
Foram recomendadas pela banca de avaliação algumas melhorias nos artefatos feitos para o Ponto de Controle 2. Eles são:

- [x] Tornar todos os artefatos rastreáveis, por meio de tabelas com nomes dos integrantes que participaram daquela documentação e datas de modificações e edições.
- [x] Ampliar o escopo nas perguntas do Forms.
- [x] Associar os requisitos levantados às técnicas de elicitação empregadas para encontrá-los.
- [x] Tornar o Brainstorm mais robusto, com texto de apoio a imagem que já está no documento.
- [x] Classificar requisitos como funcionais ou não funcionais

**Comment by Wictorgirardi** [comment]
Considerando que 4 dos 5 Checks foram realizados com sucesso e que o check de 'Ampliar o escopo nas perguntas do Forms.' não pode ser realizado devido ao já fechamento do forms essa issue esta sendo considerada fechada. Parabens time! @gustable42 @lucasgandac @Andreabenf @jonjon667 @danieloda :)
