### ISSUE TITLE
Desenvolver Product Backlog

### ISSUE THREAD

**Issue by gustable42** [Requisitos-de-Software/2019.2-Rappi#17]
O Product Backlog é feito com base nos Users Stories levantados pelos requisitos funcionais do sistema, além de definir as Tasks de cada User Story, cada Task dessa representa um item do Backlog.

**Tarefas:**
- [ ] Gerar o Product Backlog abrangendo todos os User Stories.

**Critério de Aceitação**
- [ ] Utilizar o documento de User Stories para listagem do Backlog

**Comment by lucasgandac** [comment]
Issue realizada com sucesso
