### ISSUE TITLE
Decidindo técnicas de elicitação

### ISSUE THREAD

**Issue by lucasgandac** [Requisitos-de-Software/2019.2-Rappi#2]
### Descrição:
Nós, como grupo de requisitos, devemos decidir quais técnicas de elicitação serão usadas.

### Critérios de Aceitação
- [ ] As técnicas escolhidas devem estar congruntes às técnicas ensinadas.

### Tarefas
- [ ] Decidir as técnicas usadas. 

### Comentários
Nenhum.

**Comment by gustable42** [comment]
As técnicas foram decididas e documentadas cada uma em uma issue própria, são elas:
<lu>
<li>Brainstorm - issue #3 </li>
<li>Questionário - issue #4 </li>
<li>Instrospecção - issue #5 </li>
<li> Observação - issue #6 </li>
</lu>
