### ISSUE TITLE
Desenvolver NFR no papel

### ISSUE THREAD

**Issue by gustable42** [Requisitos-de-Software/2019.2-Rappi#21]
A NFR Framework é utilizado para definir as relações e impactos entre os requisitos não funcionais e todos os requisitos funcionais relacionados a eles. A framework possui diversas regras e termos próprios dela, então aqueles que forem responsáveis por esta issue deve ter tudo isso em conta.

**Tarefas:**
- [x] Desenvolver o NFR em folhas de papeis.
- [x] Documentar cada um dos grafos gerados.

**Critérios de Aceitação:**
- [x] Todo o conteúdo deve ser entendível e legível.
- [x] Todo o conteúdo deve estar de acordo com o embasamento teórico da framework.
- [x] Todos os grafos devem ser documentados.

**Comment by Wictorgirardi** [comment]
@jonjon667 e @Andreabenf Realizaram essa task!
