### ISSUE TITLE
Transferir o NFR de papel para versão digital

### ISSUE THREAD

**Issue by gustable42** [Requisitos-de-Software/2019.2-Rappi#22]
Existe uma ferramenta para esta transferência neste link: https://personal.utdallas.edu/~supakkul/tools/RE-Tools/download-installation.html . Há a recomendação da mesma no material teórico do professor, parece que só roda em Windows. Caso se torne inviável ou o tempo hábil seja pequeno, a digitalização feita na issue #21 dos artefatos no papel será aceitável.

**Tarefas:**
- [x] Estudar a viabilidade de uso da ferramenta sugerida pelo professor.
- [x] Utilizar a ferramenta para fazer a transferência.

**Comment by Wictorgirardi** [comment]
O NFR foi realizado diretamente na ferramenta digital, nao havendo assim a necessidade de passar o documento para a ferramenta
