### ISSUE TITLE
Realizar técnica de introspecção

### ISSUE THREAD

**Issue by gustable42** [Requisitos-de-Software/2019.2-Rappi#5]
### Descrição:
Até dois membros do grupo realizará a técnica de introspecção no app, e depois, compararão suas impressões para encontrar um denominador comum entre ambas análises.

### Critérios de Aceitação
- [x] Processo deve ser realizado corretamente de acordo com a técnica.

### Tarefas
- [x] Realizar a introspecção em cima do app da Rappi.

**Comment by lucasgandac** [comment]
Tarefa referente a issue realizada.
