### ISSUE TITLE
Realizar técnica de observação

### ISSUE THREAD

**Issue by gustable42** [Requisitos-de-Software/2019.2-Rappi#6]
### Descrição:
Cada membro do grupo deve encontrar algum usuário novo ou já experiente do app da Rappi, e fazer a técnica de observação com eles, anotando pontos importantes do uso daquele usuário e possíveis comentários feitos pelo mesmo

### Critérios de Aceitação
- [ ] Processo deve ser realizado corretamente de acordo com a técnica.
- [ ] Ao menos 5 pessoas devem ser observadas para o teste ser válido.

### Tarefas
- [ ] Realizar a técnica de observação.

**Comment by lucasgandac** [comment]
Tarefa referente a issue realizada com sucesso.
